name: IsleMinecraft
main: me.lettucedealer.minecraftisle.Main
version: 0.0.3
api-version: 1.16
author: lettucedealer
description: how

commands:
  Tprandom:
  Tptome:
  Tpto:
  Artifacta:
  Artifactb: